spring.application.name=sausage-store
management.security.enabled=false

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

# протокол, по которому доступно API Vault, в проде лучше сделать https
spring.cloud.vault.enabled=true

spring.cloud.vault.scheme=http
spring.cloud.vault.kv.enabled=true

spring.cloud.vault.host=158.160.31.54
spring.cloud.vault.port=8201

spring.config.import=vault://secret/${spring.application.name}

# is supposed be filled by env variable, which in turn comes from github actions
spring.cloud.vault.token=${SPRING_CLOUD_VAULT_TOKEN}

# Enable Flyway
spring.flyway.enabled=true
flyway.baselineOnMigrate=true

#H2 settings
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
management.endpoint.prometheus.enabled=true
management.endpoints.web.exposure.include=health,prometheus
management.metrics.distribution.percentiles-histogram.http.server.requests=true
